### ISSUE TITLE
Trying to reproduce

### ISSUE THREAD

**Issue by Sleuthgame** [mriale/PyDPainter#51] opened 2023-04-22 09:48 UTC
![image](https://user-images.githubusercontent.com/130657737/233776564-b9def1a1-baa4-487b-8d26-390402b2e92b.png)

I was landing on spare page with airbrush / 2nd default brush selected. I'll try to reproduce.

**Comment by mriale** [comment] 2023-04-22 13:19
It looks like you were drawing rectangles maybe in symmetry mode when it happened. I added code to convert the coordinates to integers which should fix the crash. I wish there was a way to verify it works.

**Comment by Sleuthgame** [comment] 2023-04-22 13:48
I have another similar one. This time with Magnify. Seems changing colors and creating new gradients range 1 and 2 disturb something. I'm trying to follow this lead.

**Comment by Sleuthgame** [comment] 2023-04-22 14:00
I KNOW HOW TO REPRODUCE !
Palette : change colors, create a new color range 1. Use Cycle mode, draw with anything. Use spare or magnify, it crash again.

![image](https://user-images.githubusercontent.com/130657737/233789284-845f2967-ea84-4260-b1c3-cfb98fe1d91d.png)

**Comment by Sleuthgame** [comment] 2023-04-22 14:09
Again. Palette, create a new gradiant, a new range of color. Use it. Wait a while... BOUM !
![image](https://user-images.githubusercontent.com/130657737/233789745-a384af9b-2b53-48df-a7cf-d22b59b259eb.png)

![image](https://user-images.githubusercontent.com/130657737/233789615-e3780f4e-0824-4557-af56-34e407d2fad4.png)
(v 1.0.8)

**Comment by mriale** [comment] 2023-04-25 01:09
Thank you for persisting with this and finding out exactly how to trigger this weird bug! With your instructions, I was able to reproduce the problem in 1.0.8. The version on the `develop` branch I committed 2 days ago doesn't have this problem anymore.

**Closed** 2023-04-25 01:09 UTC
Labels: bug
